spring:
  profiles: test
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/spring_boot_core?useUnicode=true&autoReconnect=true
    username: root
    password: password

    jmx-enabled: true
    initialSize: 5
    maxActive: 100
    minIdle: 5
    maxIdle: 25
    maxAge: 3600000
    timeBetweenEvictionRunsMillis: 10000
    minEvictableIdleTimeMillis: 10000
    testWhileIdle: true
    testOnBorrow: true
    validationQuery: "SELECT 1"
    testOnReturn: false

server.port: 11501